GET http://localhost:3000/products

###
GET http://localhost:3000/products/1

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Product 8",
    "price": 710
}
###
PATCH http://localhost:3000/products/6

Content-Type: application/json

{
    "name": "Product 8",
    "price": 300
}
###
DELETE http://localhost:3000/products/7 HTTP/1.1

Content-Type: application/json